name: Release Extension

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          # Need this version otherwise the extension throw: java.lang.UnsupportedClassVersionError
          # The version of the Java Runtime only recognizes class file versions up to 55.0 which is Java 11
          java-version: 11
          cache: gradle
      - name: Check
        run: ./gradlew check
      - name: Build Jar
        run: ./gradlew jar
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/libs/hivemq-metrics-topic-kafka-extension-${{ github.event.release.name }}.jar
          asset_name: hivemq-metrics-topic-kafka-extension-${{ github.event.release.name }}.jar
          asset_content_type: application/java-archive